# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Basics
title: Eggs & Pool Site
email: bugscommunicationsteam@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Page used for the Jekyll Workshop that BUGS hosted on February 15, 2019.
  Feel free to copy it in its entirety!
baseurl: "/jekyll-workshop"
url: https://bugs-nyu.github.io # the base hostname & protocol for your site, e.g. http://example.com
repository: BUGS-NYU/jekyll-workshop

# Build settings
markdown: kramdown
theme: minima
strict_front_matter: true
exclude:
  - jekyll-workshop-env
  - jekyll-serve.py
  - LICENSE
  - README.md
  - Gemfile
  - Gemfile.lock
  - pysrc
  - requirements.txt

# Help on adding a theme
# theme: jekyll-theme-architect
# https://help.github.com/articles/adding-a-jekyll-theme-to-your-github-pages-site/

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
