# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: BUGS NYU
email: bugscommunicationsteam@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  BUGS is focused on the promotion of open source by engaging students in open
  source projects on the local and global scale, hosting speakers who work
  with open source in industry and philanthropy, and running events to advocate
  for open standards in subjects such as data and innovation. 

# Build settings
markdown: kramdown
theme: minima
strict_front_matter: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE

# Plugins
plugins:
  - jekyll-feed
